#include <cmath>
#include <utility>
#include "Math/Vector3D.h" // XYZVector

using XYZ = ROOT::Math::XYZVector;

std::pair<float,float> calculate_angles_to_beamline(float x, float y, float z) {
  /*
    Simple trigonometric relationship.
    Calculates the angle between: 
    - a line with point (x,y,z) passing through the origin (0,0,0)
    - the beam line
    This is correct only if:
    1) the beamline aligns with the z direction.
    2) both lines pass through the origin
    A more generic function is required for other cases.
   */
  std::pair<float,float> p;
  p.first = std::atan( y / z ); //y vs z
  p.second = std::atan( y / x ); //y vs x
  return p;
}

XYZ rotate_coordinates(XYZ p, float theta, float phi) {
  XYZ res;
  res.SetXYZ( std::cos(phi)*p.X() + std::sin(phi)*p.Z(),
	      std::sin(theta)*std::sin(phi)*p.X() + std::cos(theta)*p.Y() - std::sin(theta)*std::cos(phi)*p.Z(),
	      -std::sin(phi)*std::cos(theta)*p.X() + std::sin(theta)*p.Y() + std::cos(theta)*std::cos(phi)*p.Z() );
  return res;
}

/*
Translate point 'p' relative to a new origin 'origin'.
Translating a point by itself returns (0,0,0), i.e., it is the origin.
*/
XYZ translate_coordinates(XYZ p, XYZ origin) {
  XYZ res( p.X() - origin.X(),
	   p.Y() - origin.Y(),
	   p.Z() - origin.Z() );
  return res;
}

XYZ intersect_plane_with_line(XYZ genline1, XYZ genline2,
			      XYZ intersectline1, XYZ intersectline2,
			      XYZ planepoint) {
  /*Calculate the intersection between a line, generated from 'intersectline1'
    and 'intersectline2', and a plane, perpendicular to the line generated by 
    'genline1' and 'genline2' and containing 'planepoint'.
  */

  //vector along the line perpendicular to the plane (normal to the plane)
  XYZ n = genline2-genline1;
  //vector along the intersection line
  XYZ l = intersectline2-intersectline1;
  
  //(l cross n)*d + (intersectlinepoint-planepoint) cross n = 0
  //bot intersectline1 or intersectline2 can be used
  //https://en.wikipedia.org/wiki/Line%E2%80%93plane_intersection
  float d = ( (planepoint - intersectline1).Dot(n) );
  d /= ( l.Dot(n) );

  //point of intersection
  XYZ intersection = intersectline1 + l*d;
  return intersection;
}

float get_y_in_line(float x, float x1, float y1, float x2, float y2) {
  /*
    Calculates the y coordinate of a point in a line defined by two points,
    given the x coordinate.
  */
  float slope = std::abs(y2-y1) / std::abs(x2-x1);
  return slope*(x-x1) + y1;
}
